services:
  db:
    image: pgvector/pgvector:pg16
    container_name: odoo19-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
    restart: always

  odoo:
    build: .
    container_name: odoo19
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    environment:
      HOST: db
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./addons:/mnt/extra-addons
      - ./enterprise:/mnt/enterprise
      - ./data/filestore:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    restart: always
